services:
  - type: web
    name: autopazar-web
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: /app/docker/entrypoint.sh gunicorn config.wsgi:application -c docker/gunicorn/gunicorn.conf.py
    autoDeploy: true
    healthCheckPath: /health/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: autopazar-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: autopazar-redis
          property: connectionString
      - key: CELERY_TASK_ALWAYS_EAGER
        value: "true"
      - key: GUNICORN_WORKERS
        value: "1"
      - key: GUNICORN_THREADS
        value: "2"
      - key: GUNICORN_WORKER_CLASS
        value: "gthread"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
      - key: DEFAULT_FROM_EMAIL
        value: "no-reply@autopazar.mk"
      - key: USE_S3
        value: "false"

  - type: keyvalue
    name: autopazar-redis
    plan: free
    region: virginia
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

databases:
  - name: autopazar-db
    plan: free
    region: virginia
    databaseName: autopazar
    user: autopazar
